server:
  port: 2285

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    username: root
    password: 2285@sun
    #url: jdbc:mysql://localhost:3306/pces?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    url: jdbc:mysql://120.79.171.33:3306/pces?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.ouc.pces.entity

#showSql
logging:
  level:
    com:
      example:
        mapper: debug